%% les individus
individu(jean, m).
individu(paule, f).
individu(marcelle, f).
individu(henri, m).
individu(annie, f).
individu(tom, m).
individu(sylvie, f).
individu(luc, m).
individu(cathy, f).
individu(bernard, m).
individu(nancy, f).
individu(francis, m).
individu(corinne, f).
individu(anne, f).
individu(sam, m).
individu(audrey, f).
individu(marc, m).
individu(jules, m).
individu(aude, f).
individu(thomas, m).
individu(nicolas, m).
%% les liens paternels
pere(jean, luc).
pere(jean, bernard).
pere(henri, cathy).
pere(henri, anne).
pere(henri, nancy).
pere(henri, francis).
pere(tom, corinne).
pere(tom, sam).
pere(luc, audrey).
pere(luc, marc).
pere(bertrand, jules).
pere(francis, aude).
pere(sam, thomas).
pere(thomas, nicolas).
%% les liens maternels
mere(nancy, jules).
mere(paule, luc).
mere(paule, bernard).
mere(marcelle, francis).
mere(marcelle, nancy).
mere(annie, cathy).
mere(annie, anne).
mere(sylvie, corinne).
mere(sylvie, sam).
mere(cathy, audrey).
mere(cathy, marc).
mere(corinne, aude).
mere(aude, nicolas).
mere(anne, thomas).
